### ISSUE TITLE
GNURadio cannot find LimeSDR or soapy source blocks

### ISSUE THREAD

**Issue by aWZHY0yQH81uOYvH** [ktemkin/gnuradio-for-mac-without-macports#73]
In the latest prerelease (3.8.0.0-pre1), I can construct a flow graph containing a LimeSDR source block:
<img width="354" alt="simple_flowgraph" src="https://user-images.githubusercontent.com/32046476/67120256-cc39a480-f19d-11e9-9ad5-cbede9f2dded.png">
But when I run it, I get this error:
```Traceback (most recent call last):
  File "limetest.py", line 168, in <module>
    main()
  File "limetest.py", line 146, in main
    tb = top_block_cls()
  File "limetest.py", line 94, in __init__
    self.limesdr_source_0 = limesdr.source('', 0, '')
AttributeError: module 'limesdr' has no attribute 'source'
```

The same thing happens if I try using a Soapy source block. An osmocom source seems to work, though.

From what I [gather](https://github.com/myriadrf/gr-limesdr/issues/17), this means that GNURadio can't find the LimeSDR block's code.

For installation, I've just put the GNURadio application in my Applications folder and have installed Python 3.7.5 from python.org. I'm running macOS 10.14.6.

I assume this isn't happening to everyone, so what can I do to fix it?

**Comment by aWZHY0yQH81uOYvH** [comment]
I installed openSSL with homebrew for an unrelated project and came back and tried the same flowgraph again. Now it works. It seems that this package (or the Limesdr component) is not fully self-contained and was reliant on openSSL or one of its dependancies to function.
