### ISSUE TITLE
`KeyError: 'options'` when launching

### ISSUE THREAD

**Issue by beaugunderson** [ktemkin/gnuradio-for-mac-without-macports#75]
Just installed, seeing this when launching:

```bash
$ /Applications/GNURadio.app/Contents/MacOS/usr/bin/run-grc
WARNING:gnuradio.grc.core.platform:Slow YAML loading (libyaml not available)
Traceback (most recent call last):
  File "/Applications/GNURadio.app/Contents/MacOS/usr/bin/gnuradio-companion", line 102, in <module>
    run_main()
  File "/Applications/GNURadio.app/Contents/MacOS/usr/bin/gnuradio-companion", line 95, in run_main
    exit(main())
  File "/Applications/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/main.py", line 83, in main
    platform.build_library()
  File "/Applications/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/core/platform.py", line 197, in build_library
    utils.hide_bokeh_gui_options_if_not_installed(self.blocks['options'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'options'
```

I'm curious if it's because I was recently using 3.7 and it's trying to load the last file I had open?

I'm on macOS 10.15.4.

**Comment by beaugunderson** [comment]
Ah, this was due to a preferences issue but not the `file_open` or recent files keys; I moved my `~/.gnuradio` and it launched just fine. :)
